"""empty message

Revision ID: 810bc6cf3b58
Revises: be5b6fee0e6e
Create Date: 2024-10-07 22:07:36.945687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '810bc6cf3b58'
down_revision: Union[str, None] = 'be5b6fee0e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'created_at')
    # ### end Alembic commands ###
