"""empty message

Revision ID: a57b9feed79b
Revises: b9f723b33f76
Create Date: 2024-10-05 17:47:37.648820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a57b9feed79b'
down_revision: Union[str, None] = 'b9f723b33f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booths',
    sa.Column('booth_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booth_name', sa.String(length=100), nullable=False),
    sa.Column('organizer', sa.String(length=100), nullable=False),
    sa.Column('instagram_id', sa.String(length=100), nullable=True),
    sa.Column('booth_description', sa.Text(), nullable=False),
    sa.Column('location_description', sa.String(length=255), nullable=False),
    sa.Column('operation_hours', sa.String(length=100), nullable=False),
    sa.Column('booth_category', sa.Enum('FOOD', 'EXPERIENCE', 'OTHER', name='boothcategory'), nullable=False),
    sa.PrimaryKeyConstraint('booth_id')
    )
    op.create_table('booth_menu',
    sa.Column('menu_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booth_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=100), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=6, scale=0), nullable=False),
    sa.ForeignKeyConstraint(['booth_id'], ['booths.booth_id'], ),
    sa.PrimaryKeyConstraint('menu_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booth_menu')
    op.drop_table('booths')
    # ### end Alembic commands ###
