"""empty message

Revision ID: d341b651b75b
Revises: 20b1b2811ecb
Create Date: 2024-10-03 12:28:23.103106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd341b651b75b'
down_revision: Union[str, None] = '20b1b2811ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('category', sa.String(), nullable=False))
    op.add_column('notices', sa.Column('title', sa.String(), nullable=False))
    op.add_column('notices', sa.Column('content', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notices', 'content')
    op.drop_column('notices', 'title')
    op.drop_column('notices', 'category')
    # ### end Alembic commands ###
